# Generated by Django 3.0.7 on 2022-06-27 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='celular',
            field=models.CharField(default=0, max_length=11),
            preserve_default=False,
        ),
    ]
